### ISSUE TITLE
how can i use this to make inference ?

### ISSUE THREAD

**Issue by vishvesh098** [audeering/w2v2-how-to#35]
kindly guide me on how to make inference using this model.

**Comment by hagenw** [comment]
Looking at https://github.com/audeering/audonnx/issues/86, I guess the description under https://github.com/audeering/w2v2-how-to?tab=readme-ov-file#quick-start did not work for you?

**Comment by vishvesh098** [comment]
Yes but in the notebook where it train/test on dataset it provides result in emotion such as anger sad neutral etc. I want to get output in terms of emotion.

Actually i want to ask how to get inference in terms of emotion ? Or in other words how to convert VAD signals to emotion.

Kindly help me.

**Comment by hagenw** [comment]
The model was not trained to output emotional categories, what we do in the notebook is we use its `hidden_states` output as a feature extractor. Those features we then use to train on a database with emotional categories using a classical Support Vector Classification approach.

**Comment by vishvesh098** [comment]
Ok. Interesting. Thank you. I will try to first train the hidden states on the datasets with category and then make inference from it.

If there is some code snippet or guidance available it would be very beneficial.

**Comment by hagenw** [comment]
Most likely, you can just follow the "Use embeddings to train categorical emotion model" section from the [notebook](https://github.com/audeering/w2v2-how-to/blob/main/notebook.ipynb).
But note, that we just use a basic SVM classifier, and a small dataset. You might be interested to use another classifier and more data to fine-tune the model for the categorical emotion task.

Otherwise, you might look for models on HuggingFace, that are already trained to predict emotional categories, e.g. https://huggingface.co/ehcalabres/wav2vec2-lg-xlsr-en-speech-emotion-recognition.

**Comment by vishvesh098** [comment]
Thank you. I will look into it.

**Comment by vishvesh098** [comment]
Ok
